const WS_EVENTS = Object.freeze({
  FANBAND_IN_AREA: 'FANBAND_IN_AREA',
  FANBAND_STATUS: 'FANBAND_STATUS',
  FANBAND_REACT: 'FANBAND_REACT',
  FANBAND_ANSWER: 'FANBAND_ANSWER',
  UPCOMING_SCHEDULED_NOTIFICATION: 'UPCOMING_SCHEDULED_NOTIFICATION',
  LIVE_GAME_UPDATE: 'LIVE_GAME_UPDATE',
});

export default WS_EVENTS;
