import LINKS from 'utils/constants/links'

const AUTH_ROUTES = [
  LINKS.SIGN_IN.HREF
];

const PAGE_ROUTES = [
  LINKS.HOME.HREF,
  LINKS.NEWS.HREF,
  LINKS.SURVEY.HREF,
  LINKS.SCORE.HREF,
  LINKS.PROMO.HREF,
  LINKS.SCHEDULE.HREF,
  LINKS.CANNED.HREF,
];

export {
  AUTH_ROUTES,
  PAGE_ROUTES
};