// auth actions
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED';

// alert actions
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const SET_NEWS_NOTIFICATIONS = 'SET_NEWS_NOTIFICATIONS';
export const SET_SCORE_NOTIFICATIONS = 'SET_SCORE_NOTIFICATIONS';
export const SET_SURVEY_NOTIFICATIONS = 'SET_SURVEY_NOTIFICATIONS';
export const SET_PROMO_NOTIFICATIONS = 'SET_PROMO_NOTIFICATIONS';
export const SET_SCHEDULED_NOTIFICATIONS = 'SET_SCHEDULED_NOTIFICATIONS';
export const SET_CANNED_NOTIFICATIONS = 'SET_CANNED_NOTIFICATIONS';
export const SET_LATEST_NOTIFICATION = 'SET_LATEST_NOTIFICATION';
export const SET_LATEST_SURVEY_NOTIFICATION = 'SET_LATEST_SURVEY_NOTIFICATION';
export const SET_LATEST_NEWS_NOTIFICATIONS = 'SET_LATEST_NEWS_NOTIFICATIONS';

// game actions
export const FETCH_GAMES = 'FETCH_GAMES';
export const SET_SELECTED_GAME = 'SET_SELECTED_GAME';
export const SET_CLOSEST_UPCOMING_GAME = 'SET_CLOSEST_UPCOMING_GAME';
export const SELECT_DATE = 'SELECT_DATE';
export const SELECT_GAME = 'SELECT_GAME';
export const SET_ALERT_TO_SHOW = 'SET_ALERT_TO_SHOW';

// auxiliary actions
export const SET_PATH_TOKENS = 'SET_PATH_TOKENS';
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
export const SET_ERROR = 'SET_ERROR';

// fanband actions
export const SET_FANBANDS = 'SET_FANBANDS';
export const SET_FANBANDS_STATISTICS = 'SET_FANBANDS_STATISTICS';

// main state actions
export const SET_TICKETS = 'SET_TICKETS';
