
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED';

export const SET_ALL_NOTIFICATIONS = 'SET_ALL_NOTIFICATIONS';
export const SET_NEWS_NOTIFICATIONS = 'SET_NEWS_NOTIFICATIONS';
export const SET_SCORE_NOTIFICATIONS = 'SET_SCORE_NOTIFICATIONS';
export const SET_SURVEY_NOTIFICATIONS = 'SET_SURVEY_NOTIFICATIONS';
export const SET_PROMO_NOTIFICATIONS = 'SET_PROMO_NOTIFICATIONS';
export const SET_SCHEDULED_NOTIFICATIONS = 'SET_SCHEDULED_NOTIFICATIONS';
export const SET_CANNED_NOTIFICATIONS = 'SET_CANNED_NOTIFICATIONS';
export const SET_LATEST_NOTIFICATION = 'SET_LATEST_NOTIFICATION';
export const SET_LATEST_SURVEY_NOTIFICATION = 'SET_LATEST_SURVEY_NOTIFICATION';
export const SET_LATEST_NEWS_NOTIFICATIONS = 'SET_LATEST_NEWS_NOTIFICATIONS';

export const FETCH_GAMES = 'FETCH_GAMES';
export const SET_SELECT_GAME = 'SET_SELECT_GAME';
export const SET_CLOSEST_UPCOMING_GAME = 'SET_CLOSEST_UPCOMING_GAME';
export const FETCH_FANBANDS_STATISTICS = 'FETCH_FANBANDS_STATISTICS';
export const UPDATE_FANBANDS_STATISTICS = 'UPDATE_FANBANDS_STATISTICS';

export const SET_ACC_NOTIFICATION = 'SET_ACC_NOTIFICATION';
export const SET_ACC_DATA = 'SET_ACC_DATA';

export const SET_SIDE_DRAWER = 'SET_SIDE_DRAWER';
export const SET_PATH_TOKENS = 'SET_PATH_TOKENS';
export const SELECT_DATE = 'SELECT_DATE';
export const SELECT_GAME = 'SELECT_GAME';

