
const SET_LOADING_STATUS = 'SET_LOADING_STATUS'
const SET_CURRENT_USER = 'SET_CURRENT_USER'
const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED'

const SET_ALL_NOTIFICATIONS = 'SET_ALL_NOTIFICATIONS'
const SET_NEWS_NOTIFICATIONS = 'SET_NEWS_NOTIFICATIONS'
const SET_SCORE_NOTIFICATIONS = 'SET_SCORE_NOTIFICATIONS'
const SET_SURVEY_NOTIFICATIONS = 'SET_SURVEY_NOTIFICATIONS'
const SET_PROMO_NOTIFICATIONS = 'SET_PROMO_NOTIFICATIONS'
const SET_SCHEDULED_NOTIFICATIONS = 'SET_SCHEDULED_NOTIFICATIONS'
const SET_CANNED_NOTIFICATIONS = 'SET_CANNED_NOTIFICATIONS'
const SET_LATEST_NOTIFICATION = 'SET_LATEST_NOTIFICATION'
const SET_LATEST_SURVEY_NOTIFICATION = 'SET_LATEST_SURVEY_NOTIFICATION'
const SET_LATEST_NEWS_NOTIFICATIONS = 'SET_LATEST_NEWS_NOTIFICATIONS'

const FETCH_GAMES = 'FETCH_GAMES'
const SET_SELECT_GAME = 'SET_SELECT_GAME'
const SET_CLOSEST_UPCOMING_GAME = 'SET_CLOSEST_UPCOMING_GAME'
const FETCH_FANBANDS_STATISTICS = 'FETCH_FANBANDS_STATISTICS'
const UPDATE_FANBANDS_STATISTICS = 'UPDATE_FANBANDS_STATISTICS'

const SET_ACC_NOTIFICATION = 'SET_ACC_NOTIFICATION'
const SET_ACC_DATA = 'SET_ACC_DATA'

export {
  SET_LOADING_STATUS,
  SET_CURRENT_USER,
  SET_IS_AUTHENTICATED,
  SET_ALL_NOTIFICATIONS,
  SET_NEWS_NOTIFICATIONS,
  SET_SCORE_NOTIFICATIONS,
  SET_SURVEY_NOTIFICATIONS,
  SET_PROMO_NOTIFICATIONS,
  SET_SCHEDULED_NOTIFICATIONS,
  SET_CANNED_NOTIFICATIONS,
  SET_LATEST_NOTIFICATION,
  SET_LATEST_SURVEY_NOTIFICATION,
  SET_LATEST_NEWS_NOTIFICATIONS,
  FETCH_GAMES,
  SET_SELECT_GAME,
  SET_CLOSEST_UPCOMING_GAME,
  FETCH_FANBANDS_STATISTICS,
  UPDATE_FANBANDS_STATISTICS,
  SET_ACC_NOTIFICATION,
  SET_ACC_DATA
};
