
const SET_LOADING_STATUS = 'SET_LOADING_STATUS'
const SET_CURRENT_USER = 'SET_CURRENT_USER'
const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'

export {
  SET_LOADING_STATUS,
  SET_CURRENT_USER,
  SET_ACCESS_TOKEN,
};